### ISSUE TITLE
邮件发送错误

### ISSUE THREAD

**Issue by crazyggboom** [master-coder-ll/v2ray-web-manager#101]
2020-05-08 13:41:28.221 ERROR 9665 --- [task-AsyncExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.jhl.admin.util.EmailUtils.sendEmail(com.jhl.admin.util.EmailUtils$MailContent)

java.lang.RuntimeException: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smpt.163.com:465
	at com.jhl.admin.util.EmailUtils.sendEmail(EmailUtils.java:41)
	at com.jhl.admin.util.EmailUtils$$FastClassBySpringCGLIB$$5cdd2e35.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smpt.163.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at com.jhl.admin.util.EmailUtils.sendEmail(EmailUtils.java:38)
	... 9 common frames omitted
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smpt.163.com, 465; timeout 60000
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 11 common frames omitted
Caused by: java.net.UnknownHostException: smpt.163.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:357)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:217)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175)
	... 18 common frames omitted

试了25，265和994都不行，25提示异步错误程序无法打开

**Comment by master-coder-ll** [comment]
`smpt.163.com ` 睁大点眼睛。写错了
