### ISSUE TITLE
突然就网络中断，发现是proxy，重启对应java则回复

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#107]
## 你的问题是什么？

如何彻底避免此问题？是升级版本？

## 出现问题的情况是怎么样的？

不知如何复现

## 相关日志 java服务日志位于/opt/jar/logs

com.jhl.exception.ReleaseDirectMemoryException: 此异常忽略，声明需要回收直接内存|【当前版本已经更新】抛出异常。统一内存释放
	at com.jhl.proxy.Dispatcher.writeToOutBoundChannel(Dispatcher.java:383) ~[classes!/:3.1.4]
	at com.jhl.proxy.Dispatcher.lambda$sendNewPackageToClient$0(Dispatcher.java:314) ~[classes!/:3.1.4]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]

**Comment by master-coder-ll** [comment]
试试更新版本
