### ISSUE TITLE
一直502 无法解决

### ISSUE THREAD

**Issue by 2563411574** [master-coder-ll/v2ray-web-manager#160]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤
127.0.0.1进入502
## 相关日志 java服务日志位于/opt/jar/logs
log日志如下
2020-09-21 13:00:58.533  INFO 4045 --- [main] com.jhl.V2rayProxyApplication            : Starting V2rayProxyApplication v3.1.7 on localhost.localdomain with PID 4045 (/opt/jar/v2ray-proxy.jar started by root in /root)
2020-09-21 13:00:58.550  INFO 4045 --- [main] com.jhl.V2rayProxyApplication            : No active profile set, falling back to default profiles: default
2020-09-21 13:01:00.107  INFO 4045 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8091 (http)
2020-09-21 13:01:00.150  INFO 4045 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-21 13:01:00.151  INFO 4045 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-09-21 13:01:00.164  INFO 4045 --- [main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2020-09-21 13:01:00.283  INFO 4045 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-09-21 13:01:00.283  INFO 4045 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1458 ms
2020-09-21 13:01:00.334  INFO 4045 --- [main] com.jhl.common.constant.ProxyConstant    : The authPassword you set is :admin,如果authPassword如设置的不一致，配置有问题。[If the authPassword is inconsistent with the settings, there is a configuration problem]
2020-09-21 13:01:00.692  INFO 4045 --- [boss-1-1] com.jhl.framework.proxy.ProxyServer      : Proxying on:8081 ...
2020-09-21 13:01:00.701  INFO 4045 --- [task thread] c.j.f.task.service.MonitorService        : TrafficController:0,ReporterQueue:0,ConnectionPool:0,AccountCache:0
2020-09-21 13:01:00.701  INFO 4045 --- [task thread] c.j.f.task.service.MonitorService        : netty是否使用直接内存:true,使用量(-1为无法探知)B:0
2020-09-21 13:01:00.734  INFO 4045 --- [task thread] c.j.f.task.service.MonitorService        : UnpooledByteBufAllocator metric:UnpooledByteBufAllocator$UnpooledByteBufAllocatorMetric(usedHeapMemory: 0; usedDirectMemory: 0)
2020-09-21 13:01:00.735  INFO 4045 --- [task thread] c.j.f.task.service.MonitorService        :  PooledByteBufAllocator metric:PooledByteBufAllocatorMetric(usedHeapMemory: -1; usedDirectMemory: -1; numHeapArenas: 0; numDirectArenas: 0; tinyCacheSize: 512; smallCacheSize: 256; normalCacheSize: 64; numThreadLocalCaches: 0; chunkSize: 16777216)
2020-09-21 13:01:01.277  INFO 4045 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8091 (http) with context path ''
2020-09-21 13:01:01.302  INFO 4045 --- [main] com.jhl.V2rayProxyApplication            : Started V2rayProxyApplication in 3.63 seconds (JVM running for 4.878)
2020-09-21 13:01:02.601  INFO 4045 --- [Thread-2] c.jhl.common.constant.InternalConstant   : ===========================================
2020-09-21 13:01:02.602  INFO 4045 --- [Thread-2] c.jhl.common.constant.InternalConstant   : Welcome to v2ray-web-manager  : 3.1.7
2020-09-21 13:01:02.602  INFO 4045 --- [Thread-2] c.jhl.common.constant.InternalConstant   : The latest version :v3.1.7
2020-09-21 13:01:02.602  INFO 4045 --- [Thread-2] c.jhl.common.constant.InternalConstant   : The latest update :此版本更新不涉及`proxy`端，主要是对`admin`管理端和前端进行功能性的增强。需求来源[112]

升级此版本需要升级`admin`和前端项目`v2ray-manager-console`

增强内容：

 管理员可以同时有多个未使用的邀请码
 显示已使用的邀请码注册的账号-非管理员脱敏处理
 允许删除邀请码
 允许自定义邀请码有效期
2020-09-21 13:01:02.602  INFO 4045 --- [Thread-2] c.jhl.common.constant.InternalConstant   : ===========================================
2020-09-21 13:02:49.278  WARN 4045 --- [Thread-4] com.jhl.framework.proxy.ProxyServer      : netty 已经关闭....
2020-09-21 13:02:49.279  WARN 4045 --- [globalEventExecutor-2-2] com.jhl.framework.proxy.ProxyServer      : ReportService 已经关闭....

这是v2ray-proxy的log

2020-09-20 22:47:49.684 ERROR 12151 --- [main] com.jhl.framework.proxy.ProxyServer      : netty start exception:

java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2020-09-20 22:47:50.236 ERROR 12151 --- [main] org.apache.catalina.util.LifecycleBase   : Failed to start component [Connector[HTTP/1.1-8091]]

org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1008)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:226)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:259)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:197)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.jhl.V2rayProxyApplication.main(V2rayProxyApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:236)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1085)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1171)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:568)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1005)
	... 22 common frames omitted

2020-09-20 22:47:50.253 ERROR 12151 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8091 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8091, or configure this application to listen on another port.

这是v2ray-proxy.log.ERROR的log
求老板解决

相关输出
无
## 期望结果？
进入系统

**Comment by master-coder-ll** [comment]
java.net.BindException: 地址已在使用 ，重启

**Comment by 2563411574** [comment]
还是无法使用 我再重装尝试一下吧 谢谢老板了

**Comment by 2563411574** [comment]
老板我重装也重启了 还是502错误 是什么原因呢 

home@home-virtual-machine:~/桌面$ tail -100f /opt/jar/logs/admin.log.ERROR
2020-09-23 12:21:39.796 ERROR 6083 --- [main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.jhl.admin.AdminApplication.main(AdminApplication.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hibernate.boot.archive.internal.ArchiveHelper.getBytesFromInputStream(ArchiveHelper.java:181)
	at org.hibernate.boot.archive.internal.ArchiveHelper.getBytesFromInputStreamSafely(ArchiveHelper.java:139)
	at org.hibernate.boot.archive.spi.AbstractArchiveDescriptor.buildByteBasedInputStreamAccess(AbstractArchiveDescriptor.java:75)
	at org.hibernate.boot.archive.internal.JarFileBasedArchiveDescriptor.visitArchive(JarFileBasedArchiveDescriptor.java:117)
	at org.hibernate.boot.archive.scan.spi.AbstractScannerImpl.scan(AbstractScannerImpl.java:47)
	at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:76)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:99)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:232)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:167)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:51)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$116/1076835071.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)

**Comment by master-coder-ll** [comment]
vps 多大的内存

**Comment by 2563411574** [comment]
额 我是在VM虚拟机下安装的
8G4核的配置
不知道能不能行
后面要换到树莓派上面安装

**Comment by master-coder-ll** [comment]
> 额 我是在VM虚拟机下安装的
> 8G4核的配置
> 不知道能不能行
> 后面要换到树莓派上面安装

足够多，空闲内存1G左右就可以

**Comment by 2563411574** [comment]
那老板……这是什么原因导致的啊？

**Comment by JH2628** [comment]
运行下面命令可解决：
setsebool -P httpd_can_network_connect 1

**Comment by 2563411574** [comment]
依旧是Request failed with status code 502

**Comment by 2563411574** [comment]
会不会不支持虚拟机?

**Comment by 2563411574** [comment]
[root@localhost jar]# nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &
[1] 3790
[root@localhost jar]# nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &
[2] 3820
[1]   退出 1                nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1

这个是java那边的回传

**Comment by 2563411574** [comment]
老板你什么时候有空?远程下看看比较详细

**Comment by JH2628** [comment]
> 依旧是Request failed with status code 502

你是不是重启后，java没运行啊，我也是在虚拟机下搭建的，一开始也是登陆就502，运行这条命令后就正常了，你再试试运行下面3条命令，1分钟后再登陆试试

nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m  /opt/jar/admin.jar --spring.config.location=/opt/jar/admin.yaml > /dev/null 2>&1 &

nohup java -jar -Xms40m -Xmx40m -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=80m /opt/jar/v2ray-proxy.jar --spring.config.location=/opt/jar/proxy.yaml > /dev/null 2>&1 &

setsebool -P httpd_can_network_connect 1

**Comment by 2563411574** [comment]
> > 依旧是请求失败，状态码为502
> 
> 你是不是重启后，java没运行啊，我也是在虚拟机下建造的，一开始也是登陆就502，运行这条命令后就正常了，你再试试运行以下3条命令，1分钟后再登陆试试
> 
> nohup java -jar -Xms40m -Xmx40m -XX：MaxDirectMemorySize = 10M -XX：MaxMetaspaceSize = 80m /opt/jar/admin.jar --spring.config.location = / opt / jar / admin.yaml> / dev / null 2 >＆1＆
> 
> nohup java -jar -Xms40m -Xmx40m -XX：MaxDirectMemorySize = 10M -XX：MaxMetaspaceSize = 80m /opt/jar/v2ray-proxy.jar --spring.config.location = / opt / jar / proxy.yaml> / dev /空2>＆1＆
> 
> setsebool -P httpd_can_network_connect 1

多谢 我试试看

**Comment by 2563411574** [comment]
> > 依旧是请求失败，状态码为502
> 
> 你是不是重启后，java没运行啊，我也是在虚拟机下建造的，一开始也是登陆就502，运行这条命令后就正常了，你再试试运行以下3条命令，1分钟后再登陆试试
> 
> nohup java -jar -Xms40m -Xmx40m -XX：MaxDirectMemorySize = 10M -XX：MaxMetaspaceSize = 80m /opt/jar/admin.jar --spring.config.location = / opt / jar / admin.yaml> / dev / null 2 >＆1＆
> 
> nohup java -jar -Xms40m -Xmx40m -XX：MaxDirectMemorySize = 10M -XX：MaxMetaspaceSize = 80m /opt/jar/v2ray-proxy.jar --spring.config.location = / opt / jar / proxy.yaml> / dev /空2>＆1＆
> 
> setsebool -P httpd_can_network_connect 1

还是不行 我加一下你详细了解一下吧
我QQ2563411574
微信tao2563411574

**Comment by master-coder-ll** [comment]
不提供个人服务
