### ISSUE TITLE
JAVE CPU 几乎占用100%

### ISSUE THREAD

**Issue by Gangnamsstyle** [master-coder-ll/v2ray-web-manager#169]
## 你的问题是什么？
 JAVE CPU 几乎占用100%
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29761 root      20   0 2113704 199380   6840 S 99.0 19.6 309:52.75 java                
有问题先搜索Issues

## 出现问题的情况是怎么样的？

重现步骤

## 相关日志 java服务日志位于/opt/jar/logs
java.lang.IllegalArgumentException: 账号/密码错误
        at com.jhl.admin.service.UserService.login(UserService.java:123)
        at com.jhl.admin.controller.UserController.login(UserController.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java[root@VM-0-2-centos ~]# tail -100f /opt/jar/logs/v2ray-proxy.log.ERROR
2020-10-23 17:18:55.457 ERROR 29761 --- [worker-3-1] c.j.f.proxy.handler.ReceiverHandler      :  Receiver exceptionCaught:

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
[root@VM-0-2-centos ~]# tail -100f /opt/jar/logs/v2ray-proxy.log.ERROR
2020-10-23 17:18:55.457 ERROR 29761 --- [worker-3-1] c.j.f.proxy.handler.ReceiverHandler      :  Receiver exceptionCaught:

java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
        at io.netty.buffer.UnpooledDirectByteBuf.setBytes(UnpooledDirectByteBuf.java:575)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
相关输出

**Comment by master-coder-ll** [comment]
cpu 占满 大多数原因是 启动来多个相同的java程序，比如：启动多次admin端等等。看起来你遇到不仅仅是这一个问题

**Comment by matthuo333** [comment]
> cpu 占满 大多数原因是 启动来多个相同的java程序，比如：启动多次admin端等等。看起来你遇到不仅仅是这一个问题

我的并没有启动多次admin端，因为这台机器上并不运行admin. 但CPU 仍高，导致 proxy-v2ray不work了

![image](https://user-images.githubusercontent.com/55862904/106008113-f47ab780-60f1-11eb-9642-79f25c352046.png)

**Comment by Misaka1008611** [comment]
你这个问题我这两天也遇到了，用top -H java进程的PID查看 如果是四个work线程占用很高的话，就很可能是netty的bug导致的，可以通过更换服务器上的open jdk为官方最新版jdk解决。

**Comment by matthuo333** [comment]
> 你这个问题我这两天也遇到了，用top -H java进程的PID查看 如果是四个worker线程占用很高的话，就很可能是netty的bug（据说是什么空轮询）导致的，可以通过更换服务器上的open jdk为官方最新版jdk解决。
> 
> 更换方式可以参照以下链接：
> 
> https://www.cnblogs.com/mayytest1202/p/10852553.html

你具体是下载的JDK哪个版本？ JDK 8 , 11 OR 16?

**Comment by matthuo333** [comment]
目前使用JDK 11, 运行两天，用户数不多，cpu 在 40% +/-

**Comment by ocswor** [comment]
java 程序确实吃内存  之前一直用的是1G的机器，使用了这个以后，升级成了2G的机器  o(*￣︶￣*)o
我也改成jdk 11 试试 我猜就是netty 问题
查了下 https://github.com/netty/netty/issues/327 这个还在讨论

**Comment by matthuo333** [comment]
> java 程序确实吃内存 之前一直用的是1G的机器，使用了这个以后，升级成了2G的机器 o(_￣︶￣_)o
> 我也改成jdk 11 试试 我猜就是netty 问题
> 查了下 [netty/netty#327](https://github.com/netty/netty/issues/327) 已经关了 没看明白怎么弄

期待你的JDK 11的验证结果

**Comment by ocswor** [comment]
![CAPTURE_2021926_91436](https://user-images.githubusercontent.com/8704928/134789884-8c8bed28-83c6-4fa2-9aab-3da4ff6e5124.jpg)
效果很明显 已经降下来了

**Comment by matthuo333** [comment]
可以多运行一会，我当时升级完JDK后，也有效果。2天后又不行了

**Comment by ocswor** [comment]
确实 又升上来了, 才两天就涨到50%  难搞啊,很奇怪的bug,见过内存不断上涨的,没见过cpu 不断上涨的.
我准备写个定时脚本,每天晚上凌晨,重启下,不知道是否可以行

**Comment by matthuo333** [comment]
目前看来也只能这样了。定时检测CPU阈值，然后重启

**Comment by ocswor** [comment]
> top -Hp pid 看下是什么线程导致cpu高

![image](https://user-images.githubusercontent.com/8704928/137242899-0fd9bf3f-2c96-4744-9494-8150de0f5f45.png)

**Comment by master-coder-ll** [comment]
限制账号的连接数

**Comment by happyforver** [comment]
> 可以多运行一会，我当时升级完JDK后，也有效果。2天后又不行了

你的问题解决了吗? 也遇到一样的问题了. jdk11
