### ISSUE TITLE
已经触发最大连接数上限，当前允许最大值:16，后续一个小时账号全局连接数仅允许最大值半数接入

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#206]
## 你的问题是什么？

如题，大神，如何知道当前VPS上线的连接数？针对每个用户应该控制到多少连接数？是不是有个根据环境资源的计算模型？

## 出现问题的情况是怎么样的？

当前admin用户量（10个左右），只要刷新个网页，连接数就跑满。

## 相关日志 java服务日志位于/opt/jar/logs

2021-05-20 13:54:06.453  WARN 29023 --- [worker-3-1] c.j.f.proxy.handler.DispatcherHandler    : 已经触发最大连接数上限，当前允许最大值:16，后续一个小时账号全局连接数仅允许最大值半数接入
2021-05-20 13:54:06.453 ERROR 29023 --- [worker-3-1] c.j.f.proxy.handler.DispatcherHandler    : 建立与v2ray连接阶段发送错误

java.lang.IllegalAccessException: 获取不到账号或者连接数已经满
	at com.jhl.framework.proxy.handler.DispatcherHandler.parse(DispatcherHandler.java:180)
	at com.jhl.framework.proxy.handler.DispatcherHandler.channelRead(DispatcherHandler.java:72)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

## 期望结果？

如何做好控制？

**Comment by matthuo333** [comment]
我用的clash 客户端，上面没有多路复用的开关，所以对于多路复用未开启的，连接数这里怎么设置呢？

**Comment by master-coder-ll** [comment]
> 我用的clash 客户端，上面没有多路复用的开关，所以对于多路复用未开启的，连接数这里怎么设置呢？
可以通过管理后台设置每个账号的连接数
