### ISSUE TITLE
突然不行，重新搭建能访问web，但是依然不能上网

### ISSUE THREAD

**Issue by gogokkj** [master-coder-ll/v2ray-web-manager#210]
大佬们好！首先膜拜并感谢大神！
## 你的问题是什么？
正常访问后台，但是无法上网
有问题先搜索Issues

## 出现问题的情况是怎么样的？
用了大神这个脚本有一段时间了，昨天突然上不了网，后台访问正常，本着从小重启解决所有问题的习惯，重新搭建了一遍，依旧是可以访问后台，但是无法上网，求助各位，本人菜鸟查了力所能及的资料依然没有解决思路。本地ping节点正常。
重现步骤

## 相关日志 java服务日志位于/opt/jar/logs

v2ray-proxy.log.ERROR

2021-08-13 22:06:57.544 ERROR 1091 --- [http-nio-8091-exec-1] com.jhl.v2ray.service.V2rayService       : rmProxyAccount error:UNAVAILABLE: io exception,{"accountId":10,"host":"www.xxxx","accountNo":"linshilhs","id":"1dc3e660-634e-4609-91d2-bf46a044b5df","alterId":64,"level":0,"email":"linshi@outlook.com","inBoundTag":"6001","upTrafficLimit":10240,"downTrafficLimit":10240,"maxConnection":640,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}
2021-08-13 22:07:17.174 ERROR 1091 --- [worker-3-1] com.jhl.v2ray.service.V2rayService       : addProxyAccount error:UNAVAILABLE: io exception,{"version":1628863637135,"accountId":10,"host":"www.xxxx","accountNo":"linshilhs","id":"1dc3e660-634e-4609-91d2-bf46a044b5df","alterId":64,"level":0,"email":"linshi@outlook.com","inBoundTag":"6001","upTrafficLimit":10240,"downTrafficLimit":10240,"maxConnection":640,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}
2021-08-13 22:46:00.225 ERROR 1091 --- [http-nio-8091-exec-1] com.jhl.v2ray.service.V2rayService       : rmProxyAccount error:UNAVAILABLE: io exception,{"accountId":10,"host":"www.xxxx","accountNo":"linshilhs","id":"1dc3e660-634e-4609-91d2-bf46a044b5df","alterId":64,"level":0,"email":"linshi@outlook.com","inBoundTag":"6001","upTrafficLimit":10240,"downTrafficLimit":10240,"maxConnection":64,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}
2021-08-13 22:53:49.246 ERROR 1091 --- [worker-3-1] c.j.f.proxy.handler.DispatcherHandler    : 建立与v2ray连接阶段发送错误

java.lang.IllegalAccessException: 获取不到账号或者连接数已经满
	at com.jhl.framework.proxy.handler.DispatcherHandler.parse(DispatcherHandler.java:180)
	at com.jhl.framework.proxy.handler.DispatcherHandler.channelRead(DispatcherHandler.java:72)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

相关输出

## 期望结果？
可以上网

**Comment by gogokkj** [comment]
重新弄了ssr可以，然后重置重新搭v2，第一步完成（80端口）后依然不行。

**Comment by greatbody** [comment]
> 重新弄了ssr可以，然后重置重新搭v2，第一步完成（80端口）后依然不行。

close issue了，是搞好了么。

**Comment by gogokkj** [comment]
> 

对 后来弄好了 应该就是又重新搭 服务器应该也换了
