### ISSUE TITLE
netty 报异常

### ISSUE THREAD

**Issue by matthuo333** [master-coder-ll/v2ray-web-manager#223]
## 你的问题是什么？
正常运行，突然报如下错误：
WARN 22380 --- [boss-1-1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
有问题先搜索Issues

## 出现问题的情况是怎么样的？
不知什么激发导致，出现后，不能代理到v2r了

## 相关日志 java服务日志位于/opt/jar/logs

2022-03-13 08:46:07.897  WARN 22380 --- [boss-1-1] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:421)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:249)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:111)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:108)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:108)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:147)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

## 期望结果？
如何避免？

**Comment by iamlinhui** [comment]
修改/etc/security/limits.conf
新增
```text
* soft nofile 100001
* hard nofile 100002
root soft nofile 100001
root hard nofile 100002
* soft nofile 100001
* hard nofile 100002
root soft nofile 100001
root hard nofile 100002
* soft memlock unlimited
* hard memlock unlimited
```
重启服务器

**Comment by master-coder-ll** [comment]
连接是太多 参考 ulimit
