### ISSUE TITLE
跨云服务商组建集群失败

### ISSUE THREAD

**Issue by robyzhou** [master-coder-ll/v2ray-web-manager#245]
## 你的问题是什么？

跨云服务商组建集群失败

## 出现问题的情况是怎么样的？

step 1. Admin在企鹅云HK服务器上（当然上面也有proxy和v2ray节点），配置是2U4G，系统是Ubuntu，根据https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-install.md 进行安装，然后根据https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-conf.md 进行了配置。通过shadowrocket能**正常使用**该节点。

step 2. 在digitalocean服务器上申请了服务器，把这个做为另一个节点，添加到Admin上，配置是1U1G，系统是Ubuntu，根据https://github.com/master-coder-ll/v2ray-web-manager/blob/master/cluster.md 进行安装，然后根据https://github.com/master-coder-ll/v2ray-web-manager/blob/master/step-by-step-conf.md 进行了配置。该digitalocean节点，通过shadowrocket**无法使用**。创建服务器步骤截图如下：
![image](https://github.com/master-coder-ll/v2ray-web-manager/assets/6167223/4ebd7804-2d04-42fa-8a7d-66a771f3180d)

step 3. 我试过在企鹅云上再申请一台服务器，根据step 2的步骤创建集群，这台新的企鹅云服务器通过shadowrocket能**正常使用**。创建服务器步骤同step 2，只是IP地址不同。

step 4. 我尝试在企鹅云上telnet admin那台服务器，返回的错误是「telnet: Unable to connect to remote host: Connection refused」，在digitalocean上telnet admin那台服务器，返回错误也是一样的。

## 相关日志 java服务日志位于/opt/jar/logs
digitalocean上的日志记录如下：
1. /opt/jar/logs/v2ray-proxy.log.ERROR

> 2023-08-02 18:10:48.680 ERROR 91063 --- [worker-3-1] c.j.f.proxy.handler.DispatcherHandler    : 建立与v2ray连接阶段发送错误

> Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)

> 2023-08-02 18:21:14.873 ERROR 91249 --- [worker-3-2] com.jhl.v2ray.service.V2rayService       : addProxyAccount error:UNAVAILABLE: io exception,{"version":1690971672970,"accountId":5,"host":"xx.xx.xx.xx","accountNo":"2efk5q4","id":"27967959-1225-44ce-8096-59d6e8b612b1","alterId":0,"level":0,"email":"admin@admin.com","inBoundTag":"6001","upTrafficLimit":1024,"downTrafficLimit":1024,"maxConnection":64,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}

2. 由于节点无法使用，我在admin中将这台digitalocean的服务器节点删除，然后在digitalocean这台服务器的log中发现以下内容：
> 2023-08-02 18:24:31.877 ERROR 91249 --- [task thread] com.jhl.framework.task.FlowStatTask      : 上报失败：FlowStat(accountNo=2efk5q4, used=0, uniqueId=4fa26bfc-7f6a-4f86-8979-6c181bd59163, domain=24.199.98.176),<200,Result(code=500, message=1.存在多个相同域名，请删除重复的。2.查找返回为空 ;参数: domain24.199.98.176,level:0, obj=null),[Content-Type:"application/json", Content-Length:"132", Date:"Wed, 02 Aug 2023 10:24:31 GMT"]>
> 2023-08-02 18:24:32.434 ERROR 91249 --- [task thread] com.jhl.framework.task.FlowStatTask      : 上报失败：FlowStat(accountNo=2efk5q4, used=0, uniqueId=c3bd34bb-560b-4fa5-b7a6-3f4bf9fcf56e, domain=24.199.98.176),<200,Result(code=500, message=1.存在多个相同域名，请删除重复的。2.查找返回为空 ;参数: domain24.199.98.176,level:0, obj=null),[Content-Type:"application/json", Content-Length:"132", Date:"Wed, 02 Aug 2023 10:24:31 GMT"]>
……

相关输出

## 期望结果？
期望这台digitalocean的服务器能正常使用。

求大佬提供帮助，感激不尽！

**Comment by robyzhou** [comment]
问题信息补充：
我在服务器都安装了inetutils-inetd，在两台服务器上使用telnet，都能正常work。重新添加服务器之后，还是不能正常使用，以下是新的log

1. v2ray-proxy.log.ERROR
> com.jhl.v2ray.service.V2rayService       : addProxyAccount error:UNAVAILABLE: io exception,{"version":1691052896249,"accountId":5,"host":"24.199.98.176","accountNo":"2efk5q4","id":"27967959-1225-44ce-8096-59d6e8b612b1","alterId":0,"level":0,"email":"admin@admin.com","inBoundTag":"6001","upTrafficLimit":1024,"downTrafficLimit":1024,"maxConnection":64,"v2rayHost":"127.0.0.1","v2rayPort":6001,"v2rayManagerPort":62789,"proxyIp":"127.0.0.1"}

2. v2ray-proxy.log
> 当前账号:2efk5q4:24.199.98.176:1691052896249,连接数:2,服务器连接数:2,全局连接数:2
> 账号:2efk5q4:24.199.98.176:1691052896249,当前服务器完全断开连接,累计字节:0B
> 当前账号:2efk5q4:24.199.98.176:1691052896249,连接数:1,服务器连接数:1,全局连接数:1
> 账号:2efk5q4:24.199.98.176:1691052896249,当前服务器完全断开连接,累计字节:0B
……

**Comment by robyzhou** [comment]
状态更新：

将服务器系统重装之后，这个问题就解决了。具体原因并不清楚。
由于这台服务器之前已经配置了v2ray环境，且能正常使用。为了在v2ray-web-manager中使用这台服务器，按步骤进行了安装和配置，只是v2ray没有重装，只是把配置文件替换了一下。结果一直不work，最后把这台服务器给重新安装了一下，安装配置步骤完全根据项目文档进行，然后可以work了。

issue close
