### ISSUE TITLE
调用V2ray服务端的时候出错了，中间件那里不知道哪里出问题了

### ISSUE THREAD

**Issue by fujiankang** [master-coder-ll/v2ray-web-manager#39]
JAVA端调用V2ray出错，不知道哪里配置错了
2020-03-10 06:35:50.903  INFO 2172 --- [ntLoopGroup-3-3] com.jhl.proxy.Dispatcher                 : 关闭当前连接数后->account:q9arp0a:tmk.chvvs.com:null,：-1
2020-03-10 06:35:51.407  INFO 2172 --- [ntLoopGroup-3-4] com.jhl.cache.ProxyAccountCache          : getRemotePAccount:q9arp0a:tmk.chvvs.com
2020-03-10 06:35:51.408 ERROR 2172 --- [ntLoopGroup-3-4] com.jhl.proxy.Dispatcher                 : 建立与v2ray连接阶段发送错误e:{}

org.springframework.web.client.HttpClientErrorException$NotFound: 404 null
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:691) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:347) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at com.jhl.cache.ProxyAccountCache.getRemotePAccount(ProxyAccountCache.java:114) ~[classes!/:1.0]
        at com.jhl.cache.ProxyAccountCache.getProxyAccount(ProxyAccountCache.java:76) ~[classes!/:1.0]
        at com.jhl.proxy.Dispatcher.getProxyAccount(Dispatcher.java:194) ~[classes!/:1.0]
        at com.jhl.proxy.Dispatcher.channelRead(Dispatcher.java:101) ~[classes!/:1.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

2020-03-10 06:35:51.408  INFO 2172 --- [ntLoopGroup-3-4] com.jhl.proxy.Dispatcher                 : 关闭当前连接数后->account:q9arp0a:tmk.chvvs.com:null,：-1
2020-03-10 06:35:52.113  INFO 2172 --- [ntLoopGroup-3-5] com.jhl.cache.ProxyAccountCache          : getRemotePAccount:q9arp0a:tmk.chvvs.com
2020-03-10 06:35:52.114 ERROR 2172 --- [ntLoopGroup-3-5] com.jhl.proxy.Dispatcher                 : 建立与v2ray连接阶段发送错误e:{}

org.springframework.web.client.HttpClientErrorException$NotFound: 404 null
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:691) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:347) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at com.jhl.cache.ProxyAccountCache.getRemotePAccount(ProxyAccountCache.java:114) ~[classes!/:1.0]
        at com.jhl.cache.ProxyAccountCache.getProxyAccount(ProxyAccountCache.java:76) ~[classes!/:1.0]
        at com.jhl.proxy.Dispatcher.getProxyAccount(Dispatcher.java:194) ~[classes!/:1.0]
        at com.jhl.proxy.Dispatcher.channelRead(Dispatcher.java:101) ~[classes!/:1.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

2020-03-10 06:35:52.114  INFO 2172 --- [ntLoopGroup-3-5] com.jhl.proxy.Dispatcher                 : 关闭当前连接数后->account:q9arp0a:tmk.chvvs.com:null,：-1
`

**Comment by master-coder-ll** [comment]
NotFound: 404 null 
1. 确认你的admin端已经启动

2. 确认 proxy.yaml 中的 manager.address 已经指向admin，并且能ping 和telnet 通
