### ISSUE TITLE
配置分散式负载之后，节点服务器proxy报异常，导致节点服务用不了

### ISSUE THREAD

**Issue by simonliu9527** [master-coder-ll/v2ray-web-manager#42]
## 你的问题是什么？

有问题先搜索Issues

## 出现问题的情况是怎么样的？
在admin配置该节点（非admin所在节点，只有proxy）服务之后，客户端切换使用此节点，会访问失败，admin所在节点访问正常，查看proxy代理日志如下异常。另外，主节点proxy配置的direct内存比出现问题的节点还小，却不会出现这种问题，很奇怪。
重现步骤

## 相关日志 java服务日志位于/opt/jar/logs
/opt/jar/logs/v2ray-proxy.log
相关输出
2020-03-12 06:36:22.947  INFO 3593 --- [nioEventLoopGroup-3-2] com.jhl.proxy.Receiver                   :  HexDumpProxyBackendHandler exceptionCaught:{}

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 536870912, max: 536870912)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:726) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:681) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:215) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:821) [na:1.8.0_242]

## 期望结果？
不确定是否因为admin配置节点不正确导致，也有可能是程序本身bug。期望从节点能正常访问。

**Comment by master-coder-ll** [comment]
你下载的是多少版本的proxy,看是内存溢出

**Comment by master-coder-ll** [comment]
启动 java 使用 `-Dio.netty.leakDetectionLevel=advanced`  参数 跑一段时间，获取日志。我确认下是`内存泄漏`，还是`内存溢出`
