### ISSUE TITLE
我之前改的日志就是这么看得，有连接数啥的，这个是v2ray-proxy的日志，不对该怎么看呢

### ISSUE THREAD

**Issue by fujiankang** [master-coder-ll/v2ray-web-manager#66]
Proxy端 日志如下，无法探知，访问不了goole.com页面

2020-03-28 07:48:32.018 INFO 16040 --- [task thread] com.jhl.service.MonitorService : TrafficController:0,ReporterQueue:0,ConnectionPool:0,AccountCache:0
2020-03-28 07:48:32.019 INFO 16040 --- [task thread] com.jhl.service.MonitorService : netty是否使用直接内存:true,使用量(-1为无法探知)B:0
2020-03-28 07:53:32.019 INFO 16040 --- [task thread] com.jhl.service.MonitorService : TrafficController:0,ReporterQueue:0,ConnectionPool:0,AccountCache:0
2020-03-28 07:53:32.019 INFO 16040 --- [task thread] com.jhl.service.MonitorService : netty是否使用直接内存:true,使用量(-1为无法探知)B:0

**Comment by master-coder-ll** [comment]
没连接上服务器，你上个p

**Comment by master-coder-ll** [comment]
我看你也是会Java的 不会搞？

**Comment by fujiankang** [comment]
我是按照之前设置的，除非证书有特殊设置。用证书和不用证书，服务器v2ray服务那端，需要特殊设置么。

**Comment by master-coder-ll** [comment]
> 我是按照之前设置的，除非证书有特殊设置。用证书和不用证书，服务器v2ray服务那端，需要特殊设置么。

问非所答

**Comment by master-coder-ll** [comment]
> > 我是按照之前设置的，除非证书有特殊设置。用证书和不用证书，服务器v2ray服务那端，需要特殊设置么。
> 
> 问非所答

不行 初始化 重新安装

**Comment by fujiankang** [comment]
异常是报出来了，应该是某个地址配置的不对，或者是端口没开。才404，另外帐号管理的备注和用户是在新版里没有显示出来
2020-03-28 14:27:48.074 ERROR 12043 --- [    task thread] com.jhl.task.service.TaskService         : task thread error :{}

org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:691) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:347) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at com.jhl.task.GlobalConnectionStatTask.runTask(GlobalConnectionStatTask.java:52) ~[classes!/:1.0]
        at com.jhl.task.service.TaskService.startTask(TaskService.java:68) [classes!/:1.0]
        at com.jhl.task.service.TaskService.lambda$start$0(TaskService.java:43) [classes!/:1.0]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]

**Comment by master-coder-ll** [comment]
Proxy.yaml 配置了吗？设置了admin端地址？

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了
（2）现在可以访问，proxy文件那个manger,我有改动。帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据，

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了
（2）现在可以访问，proxy文件那个manger,我有改动。帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了
（2）现在可以访问，proxy文件那个manger,我有改动。帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据，

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了
（2）现在可以访问，proxy文件那个manger,我有改动。帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据，

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了
（2）现在可以访问，proxy文件那个manger,我有改动。
（3）帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据，前台没有渲染

**Comment by fujiankang** [comment]
（1）证书我已经部署上去了现在可以访问
（2）proxy的 application文件那个manger,我有改动，那里貌似少了个api的前缀。
（3）帐号管理的备注和用户是在新版里没有显示出来。我已经看到后台返回的数据，前台页面没有渲染数据
（4）VIP用户登陆页面报错，得需要点击下
（5）页面里的订阅地址是怎么改的，我自己打包部署显示地址是127.0.0.1。
