### ISSUE TITLE
注册邮箱收不到邮件

### ISSUE THREAD

**Issue by shaxel** [master-coder-ll/v2ray-web-manager#78]
## 你的问题是什么？

Issue 搜过了奈何太笨没解决

## 出现问题的情况是怎么样的？

stmp 已启用 收不到邮件

## 相关日志 java服务日志位于/opt/jar/logs

2020-04-09 09:34:35.396 ERROR 1420 --- [task-AsyncExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.jhl.admin.util.EmailUtils.sendEmail(com.jhl.admin.util.EmailUtils$MailContent)

java.lang.RuntimeException: java.lang.NullPointerException
	at com.jhl.admin.util.EmailUtils.sendEmail(EmailUtils.java:41) ~[classes!/:3.1.4]
	at com.jhl.admin.util.EmailUtils$$FastClassBySpringCGLIB$$5cdd2e35.invoke(<generated>) ~[classes!/:3.1.4]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
Caused by: java.lang.NullPointerException: null
	at com.jhl.admin.util.EmailUtils.sendEmail(EmailUtils.java:25) ~[classes!/:3.1.4]

## 期望结果？
正常接收

**Comment by master-coder-ll** [comment]
检查admin.yml文件有没有正确填写，错误提示有参数没有填写

**Comment by shaxel** [comment]
按照教程填的，困扰我好久，实在不知道问题在哪

admin:
  #第一次启动时候的账号和密码
  email: admin@admin.com
  password: 123456

proxy:
  #与porxy交互的密码，也是各种token的私钥
  authPassword: '123456'
  subscriptionTemplate: /subscribe/%s?type=%s&timestamp=%s&token=%s

email:
  #smtp地址
  host: smtp.exmail.qq.com
  #用户名称
  userName: name@qq.com
  #密码
  password: 123456
  #端口
  port: 465
  #默认false ,邮件不支持startTls不要开启
  startTlsEnabled: false

  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。



logging:
  file: /opt/jar/logs/admin.log
  file.max-history: 7
  level:
    root: info

server:
  port: 9091
  tomcat:
    max-threads: 5
    min-threads: 2
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:/opt/jar/db/admin.db
    username: ''
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.jhl.admin.util.SQLiteDialect
        enable_lazy_load_no_trans: true
        format_sql: ''
        show_sql: true

**Comment by master-coder-ll** [comment]
修改了配置文件需要重启服务。确定你已经使用是 配置过的配置文件

**Comment by shaxel** [comment]
重启了一遍，一个新的错误提示

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-09 16:08:52.845 ERROR 12191 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 9091 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 9091, or configure this application to listen on another port.

2020-04-09 16:08:52.856  INFO 12191 --- [main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-04-09 16:08:52.883  INFO 12191 --- [main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-04-09 16:08:52.894  INFO 12191 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-04-09 16:08:52.900  INFO 12191 --- [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

**Comment by master-coder-ll** [comment]
重启服务先要关闭服务，在启动服务！

**Comment by shaxel** [comment]
谢谢，您帮了大忙！btw outlook 要登录确认才能把邮件发出去
